### ISSUE TITLE
test/data/TestFont.ufo declares missing glyphs in public.glyphOrder

### ISSUE THREAD

**Issue by verbosus** [googlei18n/ufo2ft#101]
In the `public.glyphOrder` key of `lib.plist`, [test/data/TestFont.ufo](https://github.com/googlei18n/ufo2ft/blob/5a2c40c19f604f33399530a2c957ae8f33aa3262/tests/data/TestFont.ufo/lib.plist#L8) declares two glyphs which are actually missing from the `contents.plist` and in the `glyphs/` directory. 

While this could be a good test to see what behavior ufo2ft has when dealing with missing glyphs, in its current state it may just be an oversight?

**Comment by anthrotype** [comment]
I'm not sure it was an oversight but it's definitely legal.

> glyph names in the font may not appear in the order. The order may contain glyphs that are not in the font.

http://unifiedfontobject.org/versions/ufo3/lib.plist/

Note that a true test suite is quite lacking at the moment. Feel free to add more tests! Thanks
