### ISSUE TITLE
hmtx.lsb sometimes is off by one unit

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#106]
I noticed that, in fonts generated by fontmake, sometimes the left sidebearing of some glyphs is smaller by one unit than what I should be, and by "should" I mean the `xMin` coordinate in the glyph.
When that happens, the bit 1 of the `head` table flags is turned off by fonttools, because not all glyphs in the font have the left sidebearings equal to the respective xMin.

The problem is that ufo2ft is using `math.floor` instead of `round` when setting the left sidebearing in the hmtx table:

https://github.com/googlei18n/ufo2ft/commit/a1ee5514

It turns out that, when removing overlaps with booleanOperations, coordinates may be converted from `int` to `float` even though they remain exactly as they were, well *almost* the same, e.g. they may go from `12` to `11.9999999999999`. The loss of precision is probably due to the fact that they are scaled before being sent to pyclipper, and then the result is scaled again.

Now, when we give to `math.floor` such a value, that is going to return `11`. But we *know* that the value was really a `12`, and in fact the `xMin` coordinate in the glyf table for that glyph will be `12`,

In TTF, coordinates are always rounded to integers, and we currently do that inside the fonttools ttGlyphPen.

In CFF, coordinates may be floats, though currently fontmake-generated fonts are always rounded. Fonttools added support for a round tolerance in t2CharStringPen, but support for this hasn't been added to ufo2ft and fontmake yet.

I think that if we want the lsb to always be the same as the xMin, we need to use the same round function that we use to round the coordinates.
Otherwise we end up with lsb which may not match the xMin values in the glyf table, and the head flag 1 being turned on/off in a seemingly random fashion.

Comments?

**Comment by brawer** [comment]
Sounds very reasonable, as far as I can tell.

**Comment by anthrotype** [comment]
Done in #118
