### ISSUE TITLE
Adding Filter module

### ISSUE THREAD

**Issue by zjusbo** [googlei18n/ufo2ft#120]
This is a follow up thread of  https://github.com/googlei18n/fontmake/issues/275

**Overview**
Create ufo2ft/filter.py module, which is constructed by the private `com.github.googlei18n.ufo2ft.filters` key in ufo.lib

Some pseudocode
```python
class Filter:
  def __init__(self, ufo):
    if not ufo['com.github.googlei18n.ufo2ft.filters']:
      return
    self.transform = ...
    self.keepoverlap = ...
  def apply(ufo):
    '''Apply the filter to ufo'''
    for glyph in ufo:
        glyph.move(self.transform)
        ....
```

I was thinking of the following suggestions from Cosimo:

> The default filters would live in a sub-package, e.g. ufo2ft.filters, each in its own module. They could be based on the PointPen API (see ufoLib/pointPen.py), which is the standard way in the UFO world to manipulate outlines. They would work like "filter" pens, i.e. pens that take another pen that actually does the drawing, and before passing drawing commands to the inner pen, they do some transformations (the fonttools TransformPen is an example).

It's a great idea to make filter as a intercepter (Alternatively we will use glyph.move() provided by defcon to do the transformation, but it's less versatile than pen I guess). 

From my understanding it looks like this:

```python
# filterPen.py
class FilterPen:
  def __init__(self, ufo, pen):
    self.transform = XXXX
    self.pen = pen
  def _moveTo(self, pt):
    pt += transform
    self.pen._moveTo(pt)
  def _curveTo(self, *pts):
    for pt in *pts:
      pt += transform
    self.pen._curveTo(*pts) 

# outlineCompiler.py
def setupTable_glyf(self):
  ...
  pen = TTGlyphPen(allGlyphs)
  filterpen = FilterPen(ufo, pen)
  glyph.draw(filterpen)

def getCharStringForGlyphs(self, glyph, ..):
  pen = T2CharString...
  filterpen = FilterPen(ufo, pen)
  glyph.draw(filterpen)
```

Please correct me if I'm wrong, since I don't know how to use the pointPen.py as a base class. And this approach seems to work as well.

**Comment by anthrotype** [comment]
Maybe we don't need a specific `Filter` class; filters can just be treated as pens that take another pen as argument, apply transformations to the coordinates they receive and pass them on the other pen -- which in turn can be another filter pen, etc.

Something like this (maybe should go to `fontTools.pens.filterPen`?)

```python
from fontTools.pens.basePen import AbstractPen


class BaseFilterPen(AbstractPen):

    """ Base class for segment pens that transform coordinates and pass
    them to another pen.
    """

    def __init__(self, outPen, *args, **kwargs):
        self._outPen = outPen


class PassThroughFilterPen(BaseFilterPen):

    """Does nothing but pass commands to other pen with no modifications."""

    def moveTo(self, pt):
        self._outPen.moveTo(pt)

    def lineTo(self, pt):
        self._outPen.lineTo(pt)

    def curveTo(self, *points):
        self._outPen.curveTo(*points)

    def qCurveTo(self, *points):
        self._outPen.qCurveTo(*points)

    def closePath(self):
        self._outPen.closePath()

    def endPath(self):
        self._outPen.endPath()

    def addComponent(self, glyphName, transformation):
        self._outPen.addComponent(glyphName, transformation)
```

PointPens come from robofab originally (while segment pens originated in `fontTools`), and in fact the base class is now in `ufoLib` package. They carry more information than a segment pen, and the point-based approach lend itself better for some tasks. However, if we want to simply apply some transformations to the outlines immediately before writing glyf and CFF tables, then segment pens should be enough for our ufo2ft filters.

Defcon glyph objects support both the point-pen and the segment-pen protocol (indirectly, via converter pens, also defined in `ufoLib.pointPen`): to draw a glyph with a point pen, you use it's `drawPoint` method, to draw it with a segment pen, you use its `draw` method instead.

Note that the `cu2qu.pens.Cu2Qu` pen is already one of these filter pen; see how it's being used in ufo2ft `OutlineTTFCompiler.setupTable_glyf` method.

**Comment by anthrotype** [comment]
or actually maybe we need a `Filter` object, so we can iterate over each glyph in the UFO and instantiate filter pens with given options and the drawing pen of that glyph, returning the transformed glyph:

```python
class BaseFilter(object):

    # subclasses need to override this class attribute
    filterPenClass = None

    def __init__(self, include=frozenset(), *args, **kwargs):
        self.include = include
        self.args = args
        self.kwargs = kwargs

    def __call__(self, glyph):
        if glyph.name not in include:
            return glyph
        newGlyph = glyph.__class__()
        newGlyph.name = glyph.name
        outPen = newGlyph.getPen()
        glyph.draw(filterPenClass(outPen, *self.args, **self.kwargs))
        return newGlyph
```

I need to run now, sorry!

**Comment by adrientetar** [comment]
> filterPen.py

For affine transformations there's transformPen in fonttools.

**Comment by anthrotype** [comment]
@adrientetar of course, the fonttools' TransformPen is the archetypal filter pen, and we are definitely going to use it for affine transformations.
Here we're trying to build a more modular interface for adding other similar filters.

I like the idea of making Filter callable objects that take a glyph instance and return a new, modified glyph. Then we could accumulate their results through something like an inverse `map()`: the built-in applies the same function to list of objects, while this applies a list of callables to the same object, for example:

```python
def applyFilters(filters, glyph):
    result = glyph
    for func in filters:
        result = func(result)
    return result
```

Note that, although pens would definitely be involved in manipulating outline data, there is other glyph data that is not carried with neither segment- nor point-pens, i.e. anchors, width, sidebearings, etc. Basically pens can only do contours and components.
Our filters should be able to also apply modifications to the other glyph data, so it makes sense to have `Filter` classes that use filter pens inside their `__call__` method to deal with outlines, but can also manipulate other glyph attributes directly.

**Comment by zjusbo** [comment]
> I need to run now, sorry!

No worry Cosimo. Thanks for the instructions!

I'm thinking to implement a straightforward and workable solution in the first PR. And we can enrich it later.

I'm planning to write the FilterPen first, supporting only OffsetX and OffsetY in Transform(probably also support exclude/include parameter). 

```python
from fontTools.pens.basePen import AbstractPen

class BaseFilterPen(AbstractPen):

    """ Base class for segment pens that transform coordinates and pass
    them to another pen.
    """

    def __init__(self, outPen, *args, **kwargs):
        self._outPen = outPen


class PassThroughFilterPen(BaseFilterPen):

    """Does nothing but pass commands to other pen with no modifications."""

    def moveTo(self, pt):
        self._outPen.moveTo(pt)

    def lineTo(self, pt):
        self._outPen.lineTo(pt)

    def curveTo(self, *points):
        self._outPen.curveTo(*points)

    def qCurveTo(self, *points):
        self._outPen.qCurveTo(*points)

    def closePath(self):
        self._outPen.closePath()

    def endPath(self):
        self._outPen.endPath()

    def addComponent(self, glyphName, transformation):
        self._outPen.addComponent(glyphName, transformation)

class FilterPen(PassThroughFilterPen):
"""Does transformations based on the ufo2ft filter"""
    def __init__(self, outpen, filter):
        self._outpen = outpen
        self.filter = filter
     def moveTo(self, pt):
        # did some transformation on pt
        self._outPen.moveTo(self, transformedPt)
      # more operations.
```

**Comment by zjusbo** [comment]
Oh here comes the problem. We are so far so good with OffsetX, OffsetY or other parameters in Transform filter. 

However, if we want to support the other filter types like AddExtremes, HatchOutlineFilter, etc. I suspect we can not apply the filter via the drawing functions like moveTo(pt) or lineTo(pt), etc. We have to gather the information for all points in a glyph and modify them as a whole. 

Now we have two approaches.
1. apply filter via draw() method
2. apply filter by modify the data in glyph directly. 

I personally like the second option since code in function draw() only knows the points it has drawn and next point that will be draw. It doesn't has a big picture of the glyph.(Am I right?)

```python
class UFO2FTFilter(object):

    def __init__(self, exclude=None, filter):
        self.exclude = exclude or frozenset()
        self.filter = filter

    def __call__(self, glyph):
        newGlyph = glyph.__class__()
        newGlyph.name = glyph.name
        outPen = newGlyph.getPen()
        glyph.draw(outPen)
        if glyph.name in self.exclude: # Guarantee to create a new glyph instance
            return newGlyph
       switch(filter['name'].lower()):
           case 'transformations':
               return self.transformations(newGlyph)
           case 'addextremes':
               return self.addextremes(newGlyph)
        # some more cases

    def transformations(self, glyph):
        if filter.kwargs['offsetX']:
            glyph.move((offsetX, 0))
        # some more cases
        return glyph

def applyFilters(filters, glyph):
    result = glyph
    for func in filters:
        result = func(result)
    return result
```

And with this approach we can still accumulate the result of applyFilters .

**Comment by anthrotype** [comment]
> what's the difference between outline and contour? What is component and why do we sometimes need to decompose it?

An outline, generally speaking, comprises contours (which in turn can be seen as lists of points, or lists of segments, in turn lists of points), and/or components (references to other outlines).

>  code in function draw() only knows the points it has drawn and next point that will be draw

not necessarily; it could also append the points of the current contour in a list, and only when that is closed or ended, it can "flush" all the points that contour before proceeding to the next contour (see in `ufoLib.pointPen` or `cu2qu.pens` for the `_flushContour` method).

As regards the pseudocode above, i'd prefer if each filter class was distinct from one another and each did one thing at a time (transformations, add extremes, etc.); each with the same interface (the __init__ with filter parameters, and the __call__ which applies the filter to an individual glyph). In your example it appears as if there is a single `UFO2FTFilter` that does all.

**Comment by zjusbo** [comment]
> An outline, generally speaking, comprises contours (which in turn can be seen as lists of points, or lists of segments, in turn lists of points), and/or components (references to other outlines).

So for example, this 'Q' contains two outlines/contours/components, marked as 1 and 2 in the image.
![image](https://cloud.githubusercontent.com/assets/4302319/24312355/6752cbfa-1095-11e7-935c-f88a78208a43.png)


> not necessarily; it could also append the points of the current contour in a list, and only when that is closed or ended, it can "flush" all the points of that contour before proceeding to the next contour (see in ufoLib.pointPen or cu2qu.pens for the _flushContour method).

Good to know. So the it knows the current contour information to apply the filter behavior.

> As regards the pseudocode above, i'd prefer if each filter class was distinct from one another and each did one thing at a time (transformations, add extremes, etc.); each with the same interface (the init with filter parameters, and the call which applies the filter to an individual glyph). In your example it appears as if there is a single UFO2FTFilter that does all.

Agreed. Will separate these filters.

**Comment by anthrotype** [comment]
That Q's outline contains two (closed) contours.

**Comment by anthrotype** [comment]
As to why sometimes we need to decompose components: in CFF there can be no components (sub-shapes that repeat themselves are shared by means of so-called "subroutines", cf. compreffor); in TTF, there can be only two kinds of glyphs (besides the empty ones): simple glyphs with contours, and composite (or compound) glyphs containing only components (references to other glyphs), but not mixed contour-component glyphs. The latter sometimes are useful when drawing and are allowed in source font formats, but not in output binary formats.

**Comment by zjusbo** [comment]
> As to why sometimes we need to decompose components: in CFF there can be no components (sub-shapes that repeat themselves are shared by means of so-called "subroutines", cf. compreffor); in TTF, there can be only two kinds of glyphs (besides the empty ones): simple glyphs with contours, and composite (or compound) glyphs containing only components (references to other glyphs), but not mixed contour-component glyphs. The latter sometimes are useful when drawing and are allowed in source font formats, but not in output binary formats.

Got it. So decomposing a glyph is basically cuting off the reference link and let the composite glyph contains real contour data rather than references to other glyphs! 

```python

contourGlyph1 = [(1,2), (2,2)]
contourGlyph2 = [(2,3), (3,2)]

compositeGlyph = [contourGlyph1, contourGlyph2] # I think it also contains some position config or scaling config for these two components

mixedGlyph = [contourGlyph1, [(3,3), (2,2)]] # This is not allowed in TTF

def decompose(compositeGlyph):
  newGlyph = []
  for component in compositeGlyph:
    newGlyph.append(copy.deepcopy(component))
  return newGlyph

```

Please correct me if i'm wrong. I was confused by the word 'decompose' since I was thinking it is an operation to 'take apart' a glyph which does not make sense to me :(.  Now it is much more clear.
