### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/ufo2ft#161]
I’m trying to make reproducible font builds with font make (i.e.rebuilding the same sources gives identical binaries). Useful for many things, but for me mainly to catch any regressions in the build machinery and source repository management.

I have so far been successful except in one small bit; the `head.modified` (and `head.checkSumAdjustment`, but I suspect it is secondary to the modified bit).

ufo2ft seems to always use the current date for this field which causes it to change for each build. Linux distributions seem to be converging on using [an environment variable; `SOURCE_DATE_EPOCH`](https://reproducible-builds.org/specs/source-date-epoch/) to override the current date for such builds. Ideally ufo2ft would check if it is set and use it and fall back to the current behavior otherwise. Alternatively, it can have an argument that would set the date.

WDYT?

**Comment by anthrotype** [comment]
Sgtm. Maybe we could combine the two: i.e. add an argument to `compileOTF` and `compileTTF` functions and use that if not `None`; if `None`, we look up `os.environ` for `SOURCE_DATE_EPOCH` and use that if non empty, otherwise we use the current date.

Would you like to work on a PR?

**Comment by khaledhosny** [comment]
Hmm, looks like something else is resetting the modified date, FontTools?

**Comment by anthrotype** [comment]
yeah. you should pass `recalcTimestamp=False` to the TTFont constructor.

**Comment by khaledhosny** [comment]
Already tried that, still not working. Oh, TTFont constructor is called in two places, works now.

**Comment by khaledhosny** [comment]
Hmm, this does not work with fontmake and variable fonts, probably from varLib. May be FontTools is a better place to do this i.e. modifying the `misc.timeTools.timestampNow()` to respect the `SOURCE_DATE_EPOCH` envvar? The changes here would then be unnecessary.

**Comment by anthrotype** [comment]
oh...
alternatively, we could change varLib to it creates its TTFont with recalcTimestamp=False, here
https://github.com/fonttools/fonttools/blob/7f352b028b0f8459b6da0ae215e35b355ce1c4ee/Lib/fontTools/varLib/__init__.py#L836

**Comment by khaledhosny** [comment]
That is possible, but I feel it is cleaner to fix this in the most central place instead of having to patch all users of TTFont.

**Comment by anthrotype** [comment]
Ok, let's do that in the head table module where recalcTimestamp happens. It kind of makes sense that recalcTimestamp False means do not change head.modified, whereas True means update it, using the SOURCE_DATE_EPOCH if available, or the current time if the env var isn't set.

**Comment by khaledhosny** [comment]
I like changing `timestampNow()` because in the other place it is used (merge.py) it makes since to give it the same `SOURCE_DATE_EPOCH` treatment if one went out of his way and set it.

**Comment by anthrotype** [comment]
Sgtm
