### ISSUE TITLE
Add private key to propagate anchors

### ISSUE THREAD

**Issue by moyogo** [googlei18n/ufo2ft#170]
Add a private key to font.lib to propagate here instead of in glyphsLib. Either before or in markFeatureWriter.
See https://github.com/googlei18n/glyphsLib/pull/237#issuecomment-338153409

**Comment by moyogo** [comment]
Should we do this with a filter or in the markFeatureWriter?

**Comment by anthrotype** [comment]
yes, a filter can also do this
