### ISSUE TITLE
support "abvm" and "blwm" in MarkFeatureWriter

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#179]
we should extend the MarkFeatureWriter (or add new writer sublcass) so that we write these Indic-related features.

> The code to create mark and abvm/blwm is very similar.
First split all glyphs by Indic script and all other. For the first group, put all anchors with a name in (‘top’, ‘topleft’, ‘topright’, ‘candra’, ‘bindu’, ‘candrabindu’) into abvm and all (‘bottom’, ‘nukta’, ‘bottomleft’, ‘bottomright’) in blwm. All others are checked if they are in the top or bottom part of he letter.

https://github.com/googlei18n/glyphsLib/issues/223#issuecomment-346676346

related to #176

**Comment by pathumego** [comment]
To be clear this would process all the anchors regardless of the anchor names and script ss long as `marks` and `base glyphs` are defined?

**Comment by schriftgestalt** [comment]
I just changed that for Tibetan Glyphs doesnot write "abvm" and "blwm" but just one "mkmk" feature. And I omit the `lookupflag MarkAttachmentType` as that prohibits the attachment of marks to different anchors than the previous mark.

**Comment by anthrotype** [comment]
@schriftgestalt in your comment above, you said, referring to the anchors with non-standard names:

> All others are checked if they are in the top or bottom part of he letter.

Does that mean you cut the EM square in half and whatever is in the top half is abvm, what is below is blwm?

Also, could please you send me the list of script names for which Glyphs.app generates abvm/blwm feature? Thanks

**Comment by schriftgestalt** [comment]
> Does that mean you cut the EM square in half and whatever is in the top half is abvm, what is below is blwm?

Yes and check the anchor name is:
abvm = top, topleft, topright, candra, bindu, candrabindu
blwm = bottom, bottomleft, bottomright, nukta

> Also, could please you send me the list of script names for which Glyphs.app generates abvm/blwm feature?

devanagari, oriya, kannada, malayalam, gujarati, telugu, gurmukhi, tamil, bengali, cham

**Comment by anthrotype** [comment]
Awesome thank you!

**Comment by anthrotype** [comment]
@ohbendy @punchcutter @behdad @schriftgestalt 

In the OpenType Feature Tag registry, under "abvm" and "blwm" paragraphs, I read that these features are meant to position marks above (or below) the _base_ glyphs; and also that they provide 

> positioning information (x,y) to enable mark positioning (GPOS lookup type 4, 5).

Lookup type 4 and 5 are defined respectively as [Mark-To-Base](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#lookup-type-4-mark-to-base-attachment-positioning-subtable) and [Mark-To-Liga](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#lookup-type-5-mark-to-ligature-attachment-positioning-subtable) lookup types.

**However**, when I inspect the output of Glyphs.app, I can see that it also registers _Mark-To-Mark_ (Lookup Type 6) lookups in the blwm and abvm features.

Based on the above mentioned quotes from the spec, I believe that mkmk lookups and features should stay distinct from the abvm/blwm features.

I'm not sure what to do: should I follow Glyphs.app and add the mark-to-mark lookups to the abvm/blwm features, or should I only add mark-to-base and mark-to-liga lookups to these, and define a separate `mkmk` feature containing the mark-to-mark lookups?

**Comment by anthrotype** [comment]
ok, in this other document they say "abvm" includes 

> mark-to-base and mark-to-mark attachments for above-base marks

https://docs.microsoft.com/en-us/typography/script-development/kannada

so mark-to-mark could be in there too. I was confused by the other description only mentioning lookup type 4 and 5, sorry for the noise.
