### ISSUE TITLE
kern from kerning.plist gets ignored if kern feature exists in features.fea

### ISSUE THREAD

**Issue by punchcutter** [googlei18n/ufo2ft#187]
When contextual kerning is added in Glyphs (like explained at https://glyphsapp.com/tutorials/contextual-kerning) ufo2ft only uses that kern and ignores what is in kerning.plist. We want to have both so need to append instead of skip.

**Comment by anthrotype** [comment]
thanks Zachary. I will be possible to customize the feature writers with a special UFO.lib element, as proposed here 
https://github.com/googlei18n/ufo2ft/pull/178#issuecomment-350042380

**Comment by punchcutter** [comment]
Yes, I saw the new feature writer setup. It seems to me that the default mode for KernFeatureWriter should be "append" and not "skip" because that seems more likely, but maybe that's just me.

**Comment by anthrotype** [comment]
don't know.. it would be a backward incompatible change to set the default to append instead of skip for KernFeatureWriter.

**Comment by punchcutter** [comment]
Ok, that's fine then, but we want "append" for Noto so I guess that's something to add in the build scripts for noto-source?

**Comment by anthrotype** [comment]
I'm looking for a way to specify this custom feature writers in the glyphs source files themselves. I'm thinking about a (private) custom parameter that gets exported to the UFO.lib and thus read from ufo2ft.

**Comment by anthrotype** [comment]
How about we make "append" the default behavior of ufo2ft kern feature writer instead of the current "skip" if present?

That is what Glyphs currently does: i.e. it appends the user-provided kern code as the last lookup in the kern feature, after the auto-generated one derived from kerning.plist.

The current ufo2ft behavior was inherited from ufo2fdk. I imagine that for users of the latter, it was common to generate the kern feature with other tools (Metrics Machine, adobe's python scripts).

How many fontmake users use separate tools to write the kern feature?

**Comment by anthrotype** [comment]
technically, Glyphs.app _prepends_ the auto-generated kern feature code to the user-defined one, whereas our "append" mode does the other way around: the generated code is added at the bottom.
Hm.

**Comment by khaledhosny** [comment]
What about parsing the existing `kern` feature, and only outputting pairs that do not already exist? Or alternatively have a font lib parameter that controls the required behavior?

**Comment by anthrotype** [comment]
"append" is now the default behavior of KernFeatureWriter. Users can optionally specify the "skip" mode using the "com.github.googlei18n.ufo2ft.featureWriters" key in the UFO lib, e.g.:

```xml
    <key>com.github.googlei18n.ufo2ft.featureWriters</key>
    <array>
        <dict>
            <key>class</key>
            <string>KernFeatureWriter</string>
            <key>options</key>
            <dict>
                <key>mode</key>
                <string>skip</string>
            </dict>
        </dict>
    </array>
```

or one can also pass a list of `featureWriters` to the compileOTF and compileTTF functions, which can be either writer classes or be pre-initialized writer instances with custom options:

```python
from ufo2ft.featureWriters import KernFeatureWriter

kernWriter = KernFeatureWriter(mode="skip")
otf = compileOTF(..., featureWriters=[kernWriter])
```
