### ISSUE TITLE
openTypeNameLicense and openTypeNameLicenseURL are not written to the name table

### ISSUE THREAD

**Issue by madig** [googlei18n/ufo2ft#194]
1. Download and extract [test.tar.gz](https://github.com/googlei18n/ufo2ft/files/1587871/test.tar.gz)
2. `fontmake --keep-overlaps --no-production-names --keep-direction -o ttf -u Ubuntu-R.ufo`
3. Inspect name table and look for license fields.

They don't seem to be written to the binaries.

**Comment by anthrotype** [comment]
That is weird. I don’t see anything wrong by looking at the code that makes the name table in outlineCompiler, and the TestFont.ufo also has those fields and the generated TestFont.ttx does have nameIDs 13 and 14.
I’ll check your file once I get the chance, thanks

**Comment by anthrotype** [comment]
I just tried and it seems to work. This is what I see at the end of the name table:

```xml
    <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">
      Licensed under the Ubuntu Font Licence 1.0.
    </namerecord>
    <namerecord nameID="14" platformID="3" platEncID="1" langID="0x409">
      https://www.ubuntu.com/legal/terms-and-policies/font-licence
    </namerecord>
  </name>
```

what exactly is the issue you are seeing?

**Comment by anthrotype** [comment]
feel free to reopen with more details

**Comment by madig** [comment]
D'oh! I jumbled some files. Sorry for the noise.
