### ISSUE TITLE
restrict kern groups to those beginning with public.kern{1,2} prefix?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#204]
The UFO3 spec is clear about this point:

> 1. Kerning group names must begin with the appropriate prefix.

http://unifiedfontobject.org/versions/ufo3/groups.plist/

However, in our kernFeatureWriter we consider a group as a _kerning_ group if it used in kerning.plist, either as left, right or _both_ position.

https://github.com/googlei18n/ufo2ft/blob/b3cdd768f7d67d5f8a7e74b57fd4e28c97b40042/Lib/ufo2ft/featureWriters/kernFeatureWriter.py#L262-L277

Why is that? Is for backward compatibility with some previous UFO1-2 conventions?

Should we bother restricting the valid kerning groups to those with the right public.kern prefix only when the UFO formatVersion is 3?

Actually, i'm not even sure defcon provides a public api to retrieve the original UFO's format. The UFOReader knows that, of course, but defcon Font hides it in a `_` prefixed attribute (`_ufoFormatVersion`).

**Comment by anthrotype** [comment]
Found another related issue...

There's a `_correctUfoClassNames` method that renames kerning group names (from groups.plist) if they contain illegal characters that can't be used in features.fea.
This method calls another one `_makeFeaClassName`, which among other thins, "ensures the name starts with '@'".

But that's wrong.. In UFO3 groups.plist, kerning groups do not have the '@' prefix, they have 'public.kern1.` or `public.kern2.` prefix, and only that.

This means all the legal UFO3 group names are being treated as "illegal" by this method, and thus renamed in a nested for loop that has to update both the groups and the linked kerning dictionaries.

The "@" could simply be added at the end, while writing the actual FEA classes.

Can we drop support for pre-UFO3 kerning conventions (since it's such a mess and different tools would make it differently) and only support proper UFO3 kerning?

This would make it much clearer and simpler.

**Comment by adrientetar** [comment]
Sure. defcon is always ufo3 internally.

**Comment by anthrotype** [comment]
do you mean that, even if the UFO was version 2, when I load with defcon, it will have UFO3 public.kern1 and 2 prefixes?
If that's the case, then the kernFeatureWriter should not treat as kerning groups any group name that happens to be referenced on either sides of kerning.plist, but only those that have the correct prefix.

**Comment by adrientetar** [comment]
> do you mean that, even if the UFO was version 2, when I load with defcon, it will have UFO3 public.kern1 and 2 prefixes?

https://github.com/unified-font-object/ufoLib/blob/3d891631d95c590d9196a6ba425d2515750a550d/Lib/ufoLib/__init__.py#L271

**Comment by anthrotype** [comment]
Thanks Adrien! It looks like the only prefixes that are handled by `ufoLib.converters.convertUFO1OrUFO2KerningToUFO3Kerning` are `@MMK_L_` and `@MMK_R_` which is more than enough for me (that also wins the record for longest function name I ever).

**Comment by anthrotype** [comment]
the only supported kerning groups are those prefixed with `public.kern1.` and `public.kern2.` as in UFO3 spec.
