### ISSUE TITLE
why does kernFeatureWriter _removeConflictingKerningRules?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#205]
We have a method called `_removeConflictingKerningRules` that checks if any glyph-glyph pair constitutes an "exception" to a glyph-class or class-glyph pair, and then the `@` prefixed class name is replaced by an expanded list of glyphs minus those used in the glyph-glyph pair. Note that all the glyph-class and class-glyph kern pairs are written out as `enum pos` in the current implementation.

I think this method is redundant, because the [Adobe feature file spec](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html) says about `enum pos`:

> 6.b.ii. Enumerating pairs
> [...] Since this representation is convenient for generating a large number of specific pairs, it may be used even when some of the pairs generated by the 'enum' rules are incorrect. Specific pairs generated by an 'enum' rule may be overridden by specifying preceding single pairs. Because of this case, it is not an error when specific kern pairs conflict because they have the same glyphs. When specific kern pair rules conflict, the first rule specified is used, and later conflicting rule are skipped.

Anybody remembers why @jamesgk added this?
The docstring only says what the method does, instead of explaining why it is there.

Can/should we drop it?

**Comment by moyogo** [comment]
Doesn’t this make the kern lookups slightly smaller in some cases?

**Comment by anthrotype** [comment]
True, didn't think about that.

**Comment by anthrotype** [comment]
Thanks Denis, let's keep it then

**Comment by jamesgk** [comment]
I remember that there were once problems with conflicts between glyph-glyph and glyph-class rules.  And https://github.com/googlei18n/ufo2ft/pull/12 suggests that feaLib would not accept such conflicts. But it sounds like that's outdated and the primary motivation is to save space. Anyways, be sure to add an explanation to the docstring!

**Comment by anthrotype** [comment]
thank you James!

**Comment by anthrotype** [comment]
now that feaLib no longer raises an error on such constructs (i.e. specific pair pos followed by an enum pos with conflicting rules -> the first wins), I would like to remove this method `_remoceConflictingKerningRules` altogether for simplicity's sake. Without it, we would still produce valid FEA and the output won't be different than if we were pruning the conflicting pairs in the enum pos rules.
It does not save space, because feaLib doesn't compile the conflicting pairs anyway, only keeps the first specific pair pos.

**Comment by anthrotype** [comment]
the only argument for keep doing this is, we can get a warning from feaLib when this happens. 
But the FEA spec clearly mentions this as a valid use case (as a convenience for the user) so we may safely ignore the warning, or demote it to INFO or even DEBUG.

**Comment by moyogo** [comment]
We can stop using and remove this method. Since it’s allowed and handled properly I don’t think we even need to warn the user.

**Comment by anthrotype** [comment]
> Since it’s allowed and handled properly I don’t think we even need to warn the user.

but makeotf does warn. And the same warning message may happen if one manually writes two duplicated glyph+glyph pair pos rules (probably by mistake).

Do we want to make the logic in fonttools clever in differentiating between two conflicting (duplicate) glyph+glyph pair pos rules, on the one hand (in which we do warn), and an enum pos rule (glyph+group or group+glyph) that conflicts with a preceding glyph+glyph rule, on the other hand (in which we do not emit the warning and silently take the preexisting specific rule)?
