### ISSUE TITLE
ufo2ft uses deprecated 'glyphMap' when instantiating feaLib parser

### ISSUE THREAD

**Issue by madig** [googlei18n/ufo2ft#206]
Running fontmake on a UFO spits out these warnings:
```
  parser = feaLib.parser.Parser(feapath, glyphMap=glyphMap)
/home/nikolaus/Entwicklung/.../ufo2ft/featureCompiler.py:121: UserWarning: 'glyphMap' is deprecated; use 'glyphNames' (iterable) instead
```

**Comment by sladen** [comment]
Appears to have come from `fonttools` 3.20.0, from 2017-11:

* https://github.com/fonttools/fonttools/blob/master/NEWS.rst

```[feaLib] Parser constructor now accepts a glyphNames iterable instead of glyphMap dict. The latter still works but with a pending deprecation warning (#1104).```

Commit is:
* https://github.com/fonttools/fonttools/commit/0ff6be5ff89ec1e24469fa1171eac2f669bf60b8

The change seems to basically come down to the removal of `makeGlyphMap()` wrapper calls, and so just passing the array of strings directly.

**Comment by sladen** [comment]
Not sure why this has been closed.  The warning appears to remain.

**Comment by madig** [comment]
I just tried with all the latest versions and it is indeed gone. Might have been a stray package somewhere... now I get kern writer warnings though 😁

**Comment by anthrotype** [comment]
FYI, before you attempt to spend any time on removing those other warnings as well, I’m actually working on fixing other issues in the feature writers, and will update fontmake accordingly after that.
You can the ignore the warnings until then, thanks.
