### ISSUE TITLE
Optimize CFF's defaultWidthX and nominalWidthX values

### ISSUE THREAD

**Issue by miguelsousa** [googlei18n/ufo2ft#216]
Currently the default values for `defaultWidthX` and `nominalWidthX` are [200 and 0](https://github.com/googlei18n/ufo2ft/blob/master/Lib/ufo2ft/fontInfoData.py#L385-L386) and they are never adjusted according to the glyphs in the font. This makes for a slightly bigger CFF table when compared with what **makeotf** produces.

[otf-making-benchmark](https://github.com/adobe-type-tools/otf-making-benchmark) has two test cases.

Related issue #131 (CFF charstring width is always encoded)
Similar issue at https://github.com/typesupply/ufo2fdk/issues/34

**Comment by behdad** [comment]
Fixed in fonttools. Needs hooking up to ufo2ft.
https://github.com/fonttools/fonttools/commit/a70bca61fe8d89b355737e17335fd3a0d6bfaf5c#diff-26e31be1fca6b1254b2aa48483df0810R92

**Comment by behdad** [comment]
Would be nice to add tests.  We can simply extract glyph widths of a few different styles of fonts and import those as test. Would be nice to have AFDKO numbers for them to compare to.

**Comment by anthrotype** [comment]
Very cool, thanks Behdad! i'll hook this up to ufo2ft soon.
