### ISSUE TITLE
reproducible output: ufo2ft needs to handle timezone

### ISSUE THREAD

**Issue by sladen** [googlei18n/ufo2ft#220]
Per report by Chris Lamb on Debian bug tracker:

  * https://bugs.debian.org/890280 ("ufo2ft: please make the output reproducible")

`ufo2ft` does not currently take account of the timezone when trying to use the externally provided timestamp.  Reporter has provided a short patch here to correct the handling:

  * https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=890280;filename=ufo2ft.diff.txt;msg=5

**Comment by sladen** [comment]
@lamby has sent a pull request at:
* googlei18n/ufo2ft/pull/219

**Comment by lamby** [comment]
Thanks @sladen. I think we can close this in favour of the PR, mind you?
