### ISSUE TITLE
Change default verticalOrigin from glyph height to hhea.ascender?

### ISSUE THREAD

**Issue by mashabow** [googlei18n/ufo2ft#231]
When `verticalOrigin` is not set, OutlineCompiler currently uses the glyph height as a fallback value:

https://github.com/googlei18n/ufo2ft/blob/ed1c03804bfedb2cba621c61652dee6dece43ac8/Lib/ufo2ft/outlineCompiler.py#L38-L45

However, it seems more reasonable to use `hhea.ascender` than the glyph height. This is a very common setting especially in CJK fonts.

<img width="400" alt="verticalorigin" src="https://user-images.githubusercontent.com/6268183/37270127-dbd45df4-2610-11e8-98b3-52993c65ec17.png">

**Comment by behdad** [comment]
Ascender sounds wrong. I would have expected either ascender+descender. No?

**Comment by moyogo** [comment]
The height would be ascender+abs(descender), but for the vertical origin taking the ascender as a fallback makes sense.

**Comment by behdad** [comment]
Right. My bad. Was thinking about vertical advance.
