### ISSUE TITLE
Not rounding coordinates in CFF

### ISSUE THREAD

**Issue by behdad** [googlei18n/ufo2ft#24]
See:
http://blog.typekit.com/2015/10/01/smoother-curves-with-decimal-coordinate-values/

The gist of it is, non-integer numbers are allowed in CFF, and they seem to work.  Given that UPEM 1000 is used in CFF, and we are interpolating a lot, we should consider using those sometimes.  Now, encoding a non-integer takes 5 bytes (instead of 1 or 2 for most numbers), so we should be very cautious about this.  But would be good to think about supporting it (and in fonttools's t2CharStringPen).

Since coordinate data is encoded using relative coordinates (essentially 2d vectors), a good heuristic would be, to compare the rounding error to the magnitude of the vector, or to the individual components (x/y), or possibly even the change in direction.  So, perhaps adding a tolerance would be enough, but we have to consider different cases, test with a bunch of fonts, and decide what rule is most useful.

On the fonttools side, we need to support these three cases:
- Round everything,
- Round nothing,
- Round some things,

again, using a tolerance does all of them.  Value of 0 means don't round anything (no rounding error is tolerated).  Value of 1 means round everything (100% rounding error is tolerated!).  Values like 0.05 might be good for most workflows, specially for interpolations.

@readroberts can you share your script font with us for testing please?

**Comment by davelab6** [comment]
@readroberts ping :)

**Comment by readroberts** [comment]
I sent a copy of  BickhamScriptTestPro3-SemiBold.otf to Behdad by e-mail on Tuesday, February 23, 2016. Let me know if I need to send another copy.

**Comment by anthrotype** [comment]
The fonttools T2CharStringPen now includes a `roundTolerance` argument, since version 3.5.0.
https://github.com/fonttools/fonttools/issues/804

I guess now we need to also modify the `ufo2ft.outlineOTF.OutlineCompiler` class so it also accepts a similar `roundTolerance` argument (with default 0.5, round everything).

And finally, we need to update fontmake to allow passing the `--round-tolerance` as a command-line option.

**Comment by anthrotype** [comment]
Support for `roundTolerance` added with #118. Will now add a command-line argument to fontmake
