### ISSUE TITLE
Traceback on missing component

### ISSUE THREAD

**Issue by typoman** [googlei18n/ufo2ft#248]
Let's say there is a glyph that contains a reference to a component named ('Dcroat') but the glyph Dcroat doesn't exist in the ufo. In this case ufo2ft the compiler stops with a traceback. Instead, I think the better approach is to log a warning and continue to build the font. This could be easily addressed by checking if the key exists in font and if not move on. This is the traceback:

```python
Traceback (most recent call last):
  File "temp.py", line 5, in <module>
    otf = compileOTF(ufo)
  File "Github/ufo2ft/Lib/ufo2ft/__init__.py", line 57, in compileOTF
    glyphSet = preProcessor.process()
  File "Github/ufo2ft/Lib/ufo2ft/preProcessor.py", line 47, in process
    func(ufo, glyphSet)
  File "Github/ufo2ft/Lib/ufo2ft/filters/__init__.py", line 205, in __call__
    if include(glyph) and filter_(glyph):
  File "Github/ufo2ft/Lib/ufo2ft/filters/decomposeComponents.py", line 15, in filter
    _deepCopyContours(self.context.glyphSet, glyph, glyph, Transform())
  File "Github/ufo2ft/Lib/ufo2ft/filters/decomposeComponents.py", line 25, in _deepCopyContours
    glyphSet, parent, glyphSet[nested.baseGlyph],
KeyError: 'Dcroat'
```

**Comment by madig** [comment]
What is your use case, i.e. in what context does this happen?

**Comment by typoman** [comment]
The UFO was made in Robofont, so during the process of making the UFO if a glyph gets deleted and it was used as a component inside another glyph, then UFO glyph still contains a false component referencing to a glyph that's not there. I don't know if that answers your question but I'm using ufo2ft to compile the UFO.

**Comment by anthrotype** [comment]
I would argue that the font editor should be responsible of not leaving the sources in a broken state whereby a composite glyph is referencing as component another missing glyph.
However, I'm not against demoting this to a warning. PRs are welcome.

**Comment by anthrotype** [comment]
should be fixed in master
