### ISSUE TITLE
we should reference same mark classes in all mark2base lookup's statements

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#259]
Before 2.0.0, the MarkFeatureWriter was creating one mark2base lookup for each mark class, so all the `pos base` statements in each lookup were referencing the same mark class by definition.
Now, we write a single mark2base lookup in which the `pos base` statements may be referencing different mark classes, e.g.:

https://github.com/googlei18n/ufo2ft/blob/dbb107c8093bb8824c7e26fa69d240d3accdb548/tests/featureWriters/markFeatureWriter_test.py#L553-L554

I changed it in order to output similar code to Glyphs.app, which seems to be doing the same.

However, as I discussed in this issue https://github.com/fonttools/fonttools/issues/1273, it seems that this can be a problem:

1) the current Adobe's makeotf refuses to compile this mark feature, with a weird error message that seems unrelated (https://github.com/adobe-type-tools/afdko/commit/20af6dd516d5ba1db7df2512b4f5496229c28b3e)
2) Although Glyphs.app (which uses its own version of makeotfexe) compiles this code, it compiles it differently than the way fontTools.feaLib (our own feature compiler) compiles it. For the unreferenced mark classes, Glyphs.app adds a "default" anchor at (0, 0); fontTools instead writes a NULL offset...

The OpentType spec does not explicitly mention that MarkBasePos subtables (GPOS lookup type 4) or MarkMarkPos subtables (GPOS lookup type 6) can have NULL offsets to Anchor tables; only for MarkLigaPos (lookup type 5) it mentions this explicitly.

Given all this, we may have to revert to writing one separate mark2base lookup for each mark classes (the simplest option). Or we could group all the base glyphs that share the same mark classes (e.g. all the glyphs that have both @MC_top and @MC_bottom, etc.) and create several lookups accordingly, where all statements refer to the same mark classes.

**Comment by anthrotype** [comment]
I just noticed another issue with this approach of referencing multiple mark classes within the same lookup. We currently don't check that these markClasses are disjoint, so it can happen that we incur in an error like this when compiling the features:

https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/feaLib/builder.py#L961

```
fontTools.feaLib.error.FeatureLibError: <features>:99:9: Glyph uni17C6 cannot be in both @MC_abvm and @MC_abvm_high
```

quoting the feature file spec, for reference https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#4.f

> The mark classes used within a single lookup must be disjoint: none may include a glyph which is in another mark class that is used within the same lookup.

Now, of course if we go back to making one lookup per markClass, this problem never arises.

**Comment by behdad** [comment]
Two things:

1. A mark having two classes does not make sense. It's just bad input.  That said, it might make sense if the bases for those classes don't overlap, which, you are correct, your one-subtable-or-lookup-per-mark-class does handle.  It's better to combine as many classes as possible into one subtable for performance reasons though.  So, I suggest you inspect the NotoSansArabicUI to see if the error is legit or just source problem, before deciding if it's worth implementing.

2. Both HarfBuzz and Uniscribe continue searching if the anchor for a mark class against a base is null.  So, while not documented what it means, it's a legit thing to produce and it has a specific meaning that can be used to produce more optimized subtables.  Here's a test:

  https://github.com/harfbuzz/harfbuzz/commit/e95e031b5682809488cc965883e15404cb9cfb6a

So, to me, the AFDKO change is wrong.

**Comment by behdad** [comment]
I can probably implement a function in classifyTools to divide a set of class-sets into minimal number of non-overlapping groups.

**Comment by anthrotype** [comment]
no longer an issue, as makeotf now also is fine with compiling NULL anchors (https://github.com/adobe-type-tools/afdko/pull/499).
