### ISSUE TITLE
hhea ascent, descent, lineGap and caretOffset must be rounded to int

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#260]
Today I keep catching new :beetle:, must be my luck day :sweat_smile: 

This PR introduced a regression: https://github.com/googlei18n/ufo2ft/pull/233

we used to call `round()` on hhea.ascent, descent, lineGap and caretOffset values, but the refactored code no longer does that, leading to struct.error down the pipeline where fonttools attempts to pack the table bytes.

Should be straightforward to fix.

**Comment by moyogo** [comment]
Thanks @anthrotype!
