### ISSUE TITLE
compileOTF produces Type2 CharString that exceeds the stack size limit

### ISSUE THREAD

**Issue by irori** [googlei18n/ufo2ft#266]
(Filing here because I'm not sure which dependent library should be fixed.)

This program generates a font which reproduces the problem:
https://gist.github.com/irori/b0d5f53b6298efab4e526d68be2eab8d

Generated font is rejected by OTS because its Type2 Charstring exceeds the argument stack depth limit (48).

The above test program produces Type2 Charstrings like this:
```
[push 2 numbers] RMoveTo
[push 48 numbers] RLineTo
-90 -100 RMoveTo
10 10 10 10 10 10 10 10 10 VLineTo
EndChar
```
After `RLineTo` are common to all glyphs, so compreffor subroutinizes it, resulting in:
```
[push 2 numbers] RMoveTo
[push 48 numbers] [push 1 number] CallSubr
```
This exceeds the stack size limit.

Possible fixes:

- Make compreffor not insert `CallSubr` where the stack is full, or
- Reduce `maxstack` for [fontTools.cffLib.specializer.specializeCommands](https://github.com/fonttools/fonttools/blob/d7ac0ad3597dc0eaeb04a89a1f477ff40beaa36c/Lib/fontTools/cffLib/specializer.py#L268) by 1, so that there's always a room for a subroutine number.

**Comment by behdad** [comment]
> Reduce maxstack for fontTools.cffLib.specializer.specializeCommands by 1, so that there's always a room for a subroutine number.

This makes sense to me.
