### ISSUE TITLE
tests fail on 32 bit armhf archiutecture

### ISSUE THREAD

**Issue by rickysarraf** [googlei18n/ufo2ft#319]
When building the package on a Debian armhf 32 bit derivative, I run into the below error. Apparently, it turns out that very large values cause a problematic situation on `armhf`. Ideally, this should be solved in `Python`, but until that happens, can we please add a lower number, or a workaround on 32 bit `armhf` architectures ?

```
[  474s] =================================== FAILURES ===================================
[  474s] __________ DateStringToTimeValueTest.test_roundtrip_random_timestamp ___________
[  474s] 
[  474s] self = <tests.fontInfoData_test.DateStringToTimeValueTest object at 0xb1b53a30>
[  474s] 
[  474s]     def test_roundtrip_random_timestamp(self):
[  474s]         timestamp = random.randint(0, 10**10)
[  474s] >       ds = time.strftime("%Y/%m/%d %H:%M:%S", time.gmtime(timestamp))
[  474s] E       OverflowError: timestamp out of range for platform time_t
[  474s] 
[  474s] tests/fontInfoData_test.py:198: OverflowError
[  474s] =========================== short test summary info ============================
[  474s] FAIL tests/fontInfoData_test.py::DateStringToTimeValueTest::()::test_roundtrip_random_timestamp
[  474s] SKIP [2] .pybuild/cpython3_3.7_ufo2ft/build/tests/integration_test.py:97: skia-pathops is unavailable in debian yet
[  474s] SKIP [2] .pybuild/cpython3_3.7_ufo2ft/build/tests/integration_test.py:108: skia-pathops is unavailable in debian yet
[  474s] =============== 1 failed, 426 passed, 4 skipped in 26.47 seconds ===============
[  475s] E: pybuild pybuild:338: test: plugin distutils failed with: exit code=1: cd /usr/src/packages/BUILD/.pybuild/cpython3_3.7_ufo2ft/build; python3.7 -m pytest tests
[  475s] dh_auto_test: pybuild --test --test-pytest -i python{version} -p 3.7 returned exit code 13
[  475s] make[1]: *** [debian/rules:14: override_dh_auto_test] Error 25
[  475s] make[1]: Leaving directory '/usr/src/packages/BUILD'
[  475s] make: *** [debian/rules:6: build] Error 2
[  475s] dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
[  475s] 
[  475s] ecx1000-0 failed "build ufo2ft_2.6.0-1.dsc" at Mon Mar 11 13:22:23 UTC 2019.
[  475s] 
```

**Comment by madig** [comment]
Curious. What's the size of `time_t` on that platform?

**Comment by rickysarraf** [comment]
I do not have shell access to that machine right now. And neither do I have a local board handy. Sorry.  :-(
But the issue is persistent and also commonly seen with other projects using Python.

My quick search had led me to:
https://github.com/cherrypy/cherrypy/issues/1380
https://github.com/learningequality/ka-lite/issues/143
https://stackoverflow.com/questions/12458595/convert-timestamp-since-epoch-to-datetime-datetime
https://groups.google.com/forum/#!topic/comp.lang.python/crVP__5_dq8

**Comment by madig** [comment]
Could you somehow test if using `2 ** 31` instead of `10 ** 10` makes it work? Or would you need me to provide a branch for this?

**Comment by rickysarraf** [comment]
> Could you somehow test if using `2 ** 31` instead of `10 ** 10` makes it work? Or would you need me to provide a branch for this?

Oh!! Sorry. I did not mention here on what workaround I used. For our setup, for the time being, I lowered it down to `10 ** 9` and it succeeded well.

**Comment by madig** [comment]
Alright, thanks. I guess I can just change the number then.
