### ISSUE TITLE
TTF contours run the wrong direction.

### ISSUE THREAD

**Issue by robmck-ms** [googlei18n/ufo2ft#35]
When using https://github.com/googlei18n/fontmake/ to dump a Glyphs file to TTFs, the contour direction is reversed: they are in PostScript winding direction, which matches the original Glyphs file, but isn’t conventional. 

Behdad suggested filing the issue here as fontmake uses ufo2ft for this.

**Comment by jamesgk** [comment]
Should be fixed.
