### ISSUE TITLE
Should compileTTF() call cu2qu?

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/ufo2ft#50]
Right now I need to manually call cu2qu to convert fonts with cubic outlines before calling `compileTTF()`, but it might make some sense to do this by default in some way or another.

**Comment by adrientetar** [comment]
Agreed.

**Comment by jamesgk** [comment]
Yea, makes sense. But I don't know where to put it. The compileTTF function? The outlineTTFCompiler class? If the latter, which method? setupTable_glyf? None of these options seem ideal to me but I'm open to anything.

**Comment by behdad** [comment]
In the future we should make sure this is configurable.  In the mean time, I'm fine with calling cu2qu.

**Comment by behdad** [comment]
(with what error tolerance though?)

**Comment by khaledhosny** [comment]
One problem of calling `font_to_quadratic()` before `compileTTF()` is that it modifies the font in place which is problematic if the caller wants to continue working with the original font (e.g. a font editor exporting the font), so I think `setupTable_glyf()` is a good place to do the conversion without having to modify the source font.

I think we can add optional parameter for error tolerance to `compileTTF()`.
