### ISSUE TITLE
optionally merge TTX tables found in UFO3 data folder

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#51]
UFO3 has a 'data' folder where one could store extra, application specific data.

http://unifiedfontobject.org/versions/ufo3/data/

I propose that ufo2ft automatically merges into the compiled font any .ttx tables which it finds inside `font.ufo/data` folder, if the filename starts with the `org.fonttools.*` reverse domain.

Before I start working on the patch, I wanted to see if people liked the idea.

The immediate use case which I have in mind is merging the private TSI\* tables where Microsoft Visual TrueType stores the hinting source data.

Having ufo2ft merge these automatically upon compilation would be handy I think.

What do you guys think?

**Comment by davelab6** [comment]
I like this.I think it offers a solution to many issues with ufo

**Comment by adrientetar** [comment]
Yeah this would be also useful for things like MATH which aren't in UFO.

**Comment by khaledhosny** [comment]
Not sure I get the practical use of this. How these standalone tables will be generated? You most likely need the compiled font to build any additional tables, so naturally it will be a post processing step after compiling the UFO file, not before.

**Comment by anthrotype** [comment]
> How these standalone tables will be generated?

With ttx:

    ttx -s -t tbl1 -t tbl2 -o font.ufo/data/org.fonttools.ttx/font.ttx font.ttf

or alternatively with a custom fonttools script that calls `TTFont.saveXML`.

Yes, it's a post processing step to be applied after compiling the UFO file.
I see it mostly for storing data that is either produced by external tools (e.g. VTT), or which is not possible to generate from the UFO source with the currently available tools. Or which can't be easily stored in the UFO as private lib.plist elements.

It would be full TTX tables, as fonttools doesn't allow to merge incomplete tables, as it always create a new table instance when parsing XML data.

In the case of VTT, which already stores it's sources in private sfnt binary tables, this is the most natural option. I wouldn't like to define my own format, and maintain custom tools to parse/dump this data, as TTX already does the job.

I know I can just call the private data something like `com.daltonmaag.vttdump` and use my own post-processing script for that. I proposed it here to see if someone else may find this useful enough that we could bless it with a more generic `org.fonttools.ttx`.

**Comment by khaledhosny** [comment]
What I’m wondering about is how/when this data was generated in the first place, since it was not generated from the UFO file, so it looks like something that is done after compiling the font not before so why is there a need to store it in the UFO any way? But may be I’m just not understanding your work flow.

**Comment by khaledhosny** [comment]
Also, I think just storing the binary table instead of its XML dump might be better to avoid making this feature depend on FontTools. It should is easier for other tools to add a binary table to a font than to compile an XML dump.

**Comment by anthrotype** [comment]
In the case of VTT, the data was generated in a closed-source GUI-only application which happens to read/write binary TTFs. Storing it inside the UFO3 data folder makes sense to me because it pertains to each specific font.

> It should is easier for other tools to add a binary table to a font than to compile an XML dump

maybe, although you lose the advantages of text (human-readable, git friendly, etc.).

**Comment by davelab6** [comment]
The TTX format has an existing and standard way of storing binary table
data as binary data; this is how it deals with unknown tables.

**Comment by sladen** [comment]
@khaledhosny, there is considerable value in being able to eye-ball the diffs for good provenance.  In this case (some) form of plain-text representation is considerably more valuable than a binary, or base64 form.

(It's possible that better 1:1 encodings exist for the plain-text representation; and I'd certainly be interested in hearing suggestions/recommendations if the TTX form is felt inappropriate; and indeed perhaps the mechanism should be designed from the start to cope with multiple encoding possibilities).

**Comment by anthrotype** [comment]
just to clarify: when i say VTT stores its sources in the "binary" private tables, I just mean that they are stored in the compiled font, I don't mean they are binary data. It's actually UTF-8 encoded plain text, containing the VTT Talk and assembly source code.

**Comment by behdad** [comment]
Sounds useful to me.

Since we don't have fonttools.org, how about we use the Python module namespace instead?  That would be fontTools.ttx.

**Comment by anthrotype** [comment]
oh, no... Frank Blokland registered it first 😢 

> how about we use the Python module namespace instead?

The problem is the UFO spec explicitly says "To make a reverse domain, reverse the relevant *Internet* domain."

Since we currently don't have a website -- nor we actually need one, since Github is more than enough --, we could create a new Github organization called "fonttools", so we can get `github.com/fonttools` page (the name is still available), and then use `com.github.fontools.*` as the reverse domain for the UFO3 data.

We could, but we *don't have to* also transfer the whole `behdad/fonttools` repository to `fonttoos/fonttools`.

WDYT?

**Comment by behdad** [comment]
As much as I like having `behdad/fonttools`, Just also suggested we move to an org in Berlin, so I just went ahead and registered the org.  I'll add people to it for now and do the move at some point...  So yeah, I think org.github.fonttools sounds about right.

**Comment by anthrotype** [comment]
Thanks Behdad! 👍

**Comment by anthrotype** [comment]
Hey Behdad, why don't we use the old TTX icon for the organization avatar?
I mean the one that was used for the Windows executables:
 
![TTX.ico](https://dl.dropboxusercontent.com/u/189038/ttx.png)

**Comment by behdad** [comment]
> Hey Behdad, why don't we use the old TTX icon for the organization avatar?
> I mean the one that was used for the Windows executables:
> 
> TTX.ico

Just did, but it's too small...

**Comment by anthrotype** [comment]
I guess it's better than nothing for now ;)

**Comment by davelab6** [comment]
fonttools.net available

**Comment by behdad** [comment]
A few years ago I decided buying a domain for every project is pointless...

**Comment by adrientetar** [comment]
It is a big deal is the domain does not exist? Reverse domain looks mostly as a way to generate unique names, afaict.

**Comment by behdad** [comment]
> Reverse domain looks mostly as a way to generate unique names, afaict.

But the uniqueness comes from the fact that only one person can own a domain at any time ;).

**Comment by adrientetar** [comment]
> But the uniqueness comes from the fact that only one person can own a domain at any time ;).

My point is it should be reasonable to assume that no one else will write something with fonttools in a UFO.

**Comment by davelab6** [comment]
> A few years ago I decided buying a domain for every project is pointless...

Sure, because there are so many, and we don't know how big they will become or where they will lead too... but fonttools's reinvigorated development in the last couple of years makes it worth having?

**Comment by behdad** [comment]
> A few years ago I decided buying a domain for every project is pointless...
> 
> Sure, because there are so many, and we don't know how big they will become or where they will lead too... but fonttools's reinvigorated development in the last couple of years makes it worth having?

I don't see the point (anymore).  I'm thinking about giving up harfbuzz.org as well.   See, you either redirect them to somewhere (github, whatver), in which case people will only see the redirected-to URL and spread that; or you do your own hosting, which is a pain.

**Comment by davelab6** [comment]
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by behdad** [comment]
> https://help.github.com/articles/using-a-custom-domain-with-github-pages/

What problem are you trying to solve?

**Comment by davelab6** [comment]
Will github be around longer than fonttools?

**Comment by davelab6** [comment]
Back to topic:

> I propose that ufo2ft automatically merges into the compiled font any .ttx tables which it finds inside font.ufo/data folder, if the filename starts with the org.fonttools.* reverse domain.

Should this issue be closed as 'wontfix' or left open? :)
