### ISSUE TITLE
MarkAttachmentType and UseMarkFilteringSet?

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/ufo2ft#52]
There does not seem to be a way to set custom lookup flags to the generated feature, in particular I’ve an `mkmk` anchor that needs either `MarkAttachmentType` or `UseMarkFilteringSet` lookup flags to limits the feature to the set marks that have this anchor.

Adobe’s `WriteFeaturesMarkFDK.py` seems to [almost always add `MarkAttachmentType` for `mkmk` features](https://github.com/adobe-type-tools/python-modules/blob/e155395c88dea9253509b67aea39a9b2d6bc8ce4/WriteFeaturesMarkFDK.py#L662), but I’m not sure if this is right either.

May be we can (ab)use UFO groups to some how designate some group for lookup flag?

**Comment by jamesgk** [comment]
So I just learned about these flags here, but I don't really understand the use case. I thought each of the mark/mkmk lookups generated by ufo2ft was already limited to a single anchor?

**Comment by khaledhosny** [comment]
My used case is this: There is a `mkmk` anchor between `<markA>` and `<markB>` But I can have glyph sequences like `<base><markA><markC><markD><markB>` which meant there are two marks (and may be more) between `<markA>` and `<markB>` preventing the application of the anchor. But with `MarkAttachmentType` or `UseMarkFilteringSet` I can say that this anchor applies to `<markA>` and `<markB>` only, then the engines will skip any marks in between and I get my anchor applied.

**Comment by khaledhosny** [comment]
See https://github.com/khaledhosny/mada/blob/30c9426b36d95fb605b1e5498b00e8cf1b05ba2c/tools/build.py#L42-L46

**Comment by jamesgk** [comment]
Ohh ok, I didn't understand the purpose of the flag from the spec. But this makes more sense.

I actually don't see any reason not to add the flag to every mkmk lookup. Similar to your code, but just check `if isMkmk:` and use `className` with the flag. I like that this is simpler; what do you think?

**Comment by khaledhosny** [comment]
I’m not sure if it is safe to use `UseMarkFilteringSet` for all `mkmk` features, in particular I don’t know what happens with implementations that don’t support it (it is a relatively recent addition to the spec). Also I was thinking more on the general case, since one might still want to use the flags for other mark features or with arbitrary list of glyphs.

**Comment by jamesgk** [comment]
> I’m not sure if it is safe to use `UseMarkFilteringSet` for all `mkmk` features, in particular I don’t know what happens with implementations that don’t support it (it is a relatively recent addition to the spec).

Well, this applies whether we use it for all or for any features. If we use it for some by default, I think we may as well use it for all.

> Also I was thinking more on the general case, since one might still want to use the flags for other mark features or with arbitrary list of glyphs.

Is this common? Since the script you linked to uses the flag almost always, and Glyphs seems to as well, I'd rather keep things simple here and require users to subclass the writer if they need more specialized functionality.

**Comment by khaledhosny** [comment]
> > I’m not sure if it is safe to use UseMarkFilteringSet for all mkmk features, in particular I don’t know what happens with implementations that don’t support it (it is a relatively recent addition to the spec).
>
> Well, this applies whether we use it for all or for any features. If we use it for some by default, I think we may as well use it for all.

In my original proposal, it is an explicit decision from the designer, so it is his responsibility to make sure things are working.

> >    Also I was thinking more on the general case, since one might still want to use the flags for other mark features or with arbitrary list of glyphs.
>
> Is this common? Since the script you linked to uses the flag almost always, and Glyphs seems to as well, I'd rather keep things simple here and require users to subclass the writer if they need more specialized functionality.

I’m not currently working on a font that needs the more general case (but I did in the past). Lets go with the simple solution and see how it works out.

**Comment by jamesgk** [comment]
> In my original proposal, it is an explicit decision from the designer, so it is his responsibility to make sure things are working.

So we want to avoid using the flag by default, hmm. Actually, for practical purposes is it safe to assume that mark glyphs won't have more than one anchor within _top, _bottom, etc.? In which case we could just use MarkAttachmentType, as other scripts seem to do.

**Comment by khaledhosny** [comment]
I wouldn’t be sure about this, though I just tried MarkAttachmentType here and it worked, so that is fine by me.

**Comment by jamesgk** [comment]
Based on my own experience with how these anchors are used, I personally think it's pretty safe and that this is another place where we can expect users to override default behavior if needed.

**Comment by behdad** [comment]
Do we know what Glyphs does BTW?  @schriftgestalt

**Comment by schriftgestalt** [comment]
Glyphs uses `lookupflag MarkAttachmentType @mark_bottom;`. This worked fine so far.
