### ISSUE TITLE
Default value for openTypeOS2Type

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/ufo2ft#53]
Currently if openTypeOS2Type is not set, it defaults to setting bit 2. I find this a bit surprising, shouldn’t not setting it be the same as setting it to an empty list i.e. no bits set?

**Comment by jamesgk** [comment]
Quick reference for the benefit of anyone reading: https://www.microsoft.com/typography/otspec/os2.htm#fst

I don't have a very strong opinion here, but it makes sense to me to default to the strictest setting. I'd think someone being surprised that their font has no usage restrictions is worse than someone being surprised that it does have restrictions (which they can change later).

**Comment by adrientetar** [comment]
> I don't have a very strong opinion here, but it makes sense to me to default to the strictest setting. I'd think someone being surprised that their font has no usage restrictions is worse than someone being surprised that it does have restrictions (which they can change later).

Yeah.

**Comment by adrientetar** [comment]
> Currently if openTypeOS2Type is not set, it defaults to setting bit 2. I find this a bit surprising, shouldn’t not setting it be the same as setting it to an empty list i.e. no bits set?

ufo2ft like ufo2fdk has a set of fallback values/heuristics, it does better than not setting things when they're not in the source. If you want to mark your fonts as embeddable, that should be done in the sources.

**Comment by khaledhosny** [comment]
My surprise was that I though setting it to None is equivalent to setting all bit to zero. The difference between None and am empty list is not very obvious IMHO. But I can accept the resolution here if this is the consensus.

**Comment by davelab6** [comment]
This is what Glyphs does so it seems expected for me, although I agree with
khaled

**Comment by ctrlcctrlv** [comment]
I just hit this. Weird behavior.
