### ISSUE TITLE
name table records with same record id but different platform ids and contents

### ISSUE THREAD

**Issue by davelab6** [googlei18n/ufo2ft#58]
I'm raising this issue after https://github.com/googlefonts/fontbakery/issues/853 

Since a goal is for fontmake output to match glyphsapp output when compiling .glyphs files, it seems like a needed feature request is to handle setting name records with the same record id but different platform ids and different contents. 

Specifically I want ufo2ft to make nameID=4 ("Full Name") look the same as nameID=6 ("PostScript Name") when the platformID=3 ("Windows platform")

**Comment by davelab6** [comment]
Specifically I want ufo2ft to make nameID=4 ("Full Name") look the same as nameID=6 ("PostScript Name") when the platformID=3 ("Windows platform")

**Comment by anthrotype** [comment]
For reference, here's a link to the old spec that mention this (thanks @khaledhosny for finding it):
https://web.archive.org/web/20080409142622/http://www.microsoft.com/typography/otspec/name.htm

> Full font name; this should be a combination of strings 1 and 2. Exception: if the font is "Regular" as indicated in string 2, then use only the family name contained in string 1. 
An exception to the above definition of Full font name is for Microsoft platform strings for CFF OpenType fonts: in this case, the Full font name string must be identical to the PostScript FontName in the CFF Name INDEX.

FWIW, I'm not convinced that this change is needed.

**Comment by adrientetar** [comment]
Nominating for WONTFIX

**Comment by jamesgk** [comment]
> Since a goal is for fontmake output to match glyphsapp output when compiling .glyphs files

This isn't exactly true. It definitely helped guide glyphsLib development for me to try to match UFO output. But generally I think we just want to match user expectations (which may have been set by using Glyphs). In this case it doesn't sound like matching Glyphs makes sense though.

**Comment by behdad** [comment]
> Since a goal is for fontmake output to match glyphsapp output when compiling .glyphs files
> 
> This isn't exactly true. It definitely helped guide glyphsLib development for me to try to match UFO output. But generally I think we just want to match user expectations (which may have been set by using Glyphs). In this case it doesn't sound like matching Glyphs makes sense though.

Agree.  In particular, adding Apple name-IDs is unnecessary.

**Comment by davelab6** [comment]
> adding Apple name-IDs is unnecessary

Except when your users are using an older version of MS Word for Mac, and throwing a tantrum :)

**Comment by brawer** [comment]
Actually, this seems already implemented; the current ufo2ft supports `openTypeNameRecords` in `fontinfo.plist`. For example, ufo2ft converts this:

```plist
		<key>openTypeNameRecords</key>
		<array>
			<dict>
				<key>encodingID</key>
				<integer>0</integer>
				<key>languageID</key>
				<integer>0</integer>
				<key>nameID</key>
				<integer>3</integer>
				<key>platformID</key>
				<integer>1</integer>
				<key>string</key>
				<string>Unique Font Identifier</string>
			</dict>
			<dict>
				<key>encodingID</key>
				<integer>1</integer>
				<key>languageID</key>
				<integer>1033</integer>
				<key>nameID</key>
				<integer>8</integer>
				<key>platformID</key>
				<integer>3</integer>
				<key>string</key>
				<string>Some Foundry (Manufacturer Name)</string>
			</dict>
		</array>
```

to that:

```xml
    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Unique Font Identifier
    </namerecord>
    <namerecord nameID="8" platformID="3" platEncID="1" langID="0x409">
      Some Foundry (Manufacturer Name)
    </namerecord>
```

See [tests/data/TestUfo.ufo/fontinfo.plist](https://github.com/googlei18n/ufo2ft/blob/master/tests/data/TestFont.ufo/fontinfo.plist#L138) and the corresponding result in [TestFont.ttx](https://github.com/googlei18n/ufo2ft/blob/master/tests/data/TestFont.ttx#L214).

Closing bug because there doesn’t seem to be anything missing here. But feel free to re-open if I’m wrong.

**Comment by davelab6** [comment]
OK cool :) Thanks for looking into this

**Comment by brawer** [comment]
@davelab6, a second way of doing this is [table name](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.e) in the features file. Anyhow, looks like there’s nothing left to do on this bug.

**Comment by davelab6** [comment]
Ah yes :) thanks!!
