### ISSUE TITLE
LTR/RTL kernFeatureWriter

### ISSUE THREAD

**Issue by graphicore** [googlei18n/ufo2ft#8]
I'm not sure where to put this but I think it may be interesting for the current developments in #7 and #6 etc.

I extended the [kernFeatureWriter of ufo2fdk/ufo3 branch](https://github.com/typesupply/ufo2fdk/blob/ufo3/Lib/ufo2fdk/kernFeatureWriter.py) for Jomhuria to support the creation of a fea-kerning file from ufo kerning.plist which works for LTR and RTL text.

Here: https://github.com/Tarobish/Jomhuria/blob/gh-pages/tools/getKernFeatureFromUFO.py

See this discussion unified-font-object/ufo-spec#16 where @behdad gave the hints how to approach this.

This is dependent on the ufo3k ufoLib.

If you're interested in this code we could look at how to integrate it. We should probably decide which is the best way to do RTL + LTR kerning from kerning.plist and subsequently discard some of the options from my code, to make it easier to use.

**Comment by behdad** [comment]
:+1:

**Comment by jamesgk** [comment]
Sorry for taking so long to get to this. From the linked discussion:

> Here's the simplest heuristic that works:
> 
> - Generate both an LTR kern lookup and an RTL one; including all kerning pairs in both.
> - Reference the RTL lookup from script systems that are RTL, and the LTR one for others.
> 
> That's the crudest heuristic, but it works. From there on, you can add more complexity to achieve smaller kern tables. [...] For example, a huge improvement:
> 
> - Associate each glyph to a Unicode character,
> - Exclude from RTL kern table all glyphs associated with Unicode characters that have Bidi_Type=L,
> - Exclude from LTR kern table all glyphs associated with Unicode characters that have Bidi_Type=R or Bidi_Type=AL.

Is this still the suggested approach? I don't have any better ideas.

**Comment by behdad** [comment]
> Is this still the suggested approach? I don't have any better ideas.

Yes, it is.
