### ISSUE TITLE
(bold) and (bold) should match. Don't they match already?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/ufo2ft#80]
not certain how to interpret this new warning in the pipeline
WARNING:fontTools.ttLib.tables.O_S_2f_2:fsSelection bit 5 (bold) and head table macStyle bit 0 (bold) should match

while building src/NotoSansArabicUI-MM.glyphs (possibly others)

**Comment by moyogo** [comment]
This can be closed, the regression has been fixed in fontTools.
