### ISSUE TITLE
PyPI?

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/ufo2ft#84]
Can we have ufo2ft published on PyPI?

**Comment by anthrotype** [comment]
Sorry, I got sidetracked by other things. I'll get back to this very soon.

**Comment by anthrotype** [comment]
It's live now:
https://pypi.python.org/pypi/ufo2ft
https://pypi.org/project/ufo2ft/

**Comment by anthrotype** [comment]
The packages that still needs to be published to PyPI are mutatorMath, glyphsLib and fontmake. I shall do them in that order, when time permits.
