### ISSUE TITLE
Emit table GDEF with LigatureCaretByPos statements

### ISSUE THREAD

**Issue by brawer** [googlei18n/ufo2ft#91]
Could ufo2ft generate feature files with `table GDEF` blocks, and `LigatureCaretByPos` statements for ligatures?

For example, when exporting [Noto Sans Hebrew](https://github.com/googlei18n/noto-source/blob/master/src/NotoSansHebrew-MM.glyphs) as an OpenType font, Glyphs.app generates a feature file with the following `table GDEF` block. It would be great if ufo2ft could emit something equivalent, so that the final fonts contain a GDEF table that also contains info about ligatures.

```
table GDEF {
 GlyphClassDef [alef-hb bet-hb gimel-hb dalet-hb he-hb vav-hb zayin-hb het-hb t\
et-hb yod-hb finalkaf-hb kaf-hb lamed-hb finalmem-hb mem-hb finalnun-hb nun-hb \
samekh-hb ayin-hb finalpe-hb pe-hb finaltsadi-hb tsadi-hb qof-hb resh-hb shin-h\
b tav-hb yodhiriq-hb yodyodpatah-hb ayinaltone-hb shinshindot-hb shinsindot-hb \
shindageshshindot-hb shindageshsindot-hb alefpatah-hb alefqamats-hb alefdagesh-\
hb betdagesh-hb gimeldagesh-hb daletdagesh-hb hedagesh-hb vavdagesh-hb zayindag\
esh-hb tetdagesh-hb yoddagesh-hb finalkafdagesh-hb kafdagesh-hb lameddagesh-hb \
memdagesh-hb nundagesh-hb samekhdagesh-hb finalpedagesh-hb pedagesh-hb tsadidag\
esh-hb qofdagesh-hb reshdagesh-hb shindagesh-hb tavdagesh-hb vavholam-hb betraf\
e-hb kafrafe-hb perafe-hb],# Base
 , # Liga
 [etnahtaleft-hb segolta-hb shalshelet-hb zaqefqatan-hb zaqefgadol-hb tipehalef\
t-hb reviamugrash-hb zarqa-hb pashta-hb yetiv-hb tevirleft-hb gereshaccent-hb g\
ereshmuqdam-hb gershayimaccent-hb qarneypara-hb telishagedola-hb pazer-hb atnah\
hafukh-hb munahleft-hb mahapakhleft-hb merkhaleft-hb merkhakefulaleft-hb dargal\
eft-hb qadma-hb telishaqetana-hb yerahbenyomoleft-hb ole-hb iluy-hb dehi-hb zin\
or-hb masoracircle-hb sheva-hb hatafsegol-hb hatafsegol_zerowidthjoiner_siluqle\
ft-hb hatafpatah-hb hatafpatah_zerowidthjoiner_siluqleft-hb hatafqamats-hb hata\
fqamats_zerowidthjoiner_siluqleft-hb hiriq-hb tsere-hb segol-hb patah-hb qamats\
-hb holam-hb holamhaser-hb qubuts-hb dagesh-hb siluqleft-hb rafe-hb shindot-hb \
sindot-hb upperdot-hb lowerdot-hb qamatsqatan-hb judeospanishvarika-hb], # Mark\

 ;
 LigatureCaretByPos vavvav-hb 221;
LigatureCaretByPos vavyod-hb 206;
LigatureCaretByPos yodyod-hb 191;
LigatureCaretByPos aleflamed-hb 242;
} GDEF;
```

**Comment by anthrotype** [comment]
Yes, that would be useful indeed.
How does Glyphs.app determines the `GlyphClassDef` for each glyph?
From the [`GlyphsData.xml`](https://github.com/schriftgestalt/GlyphsInfo/blob/master/GlyphData.xml) database?

/cc @schriftgestalt

**Comment by adrientetar** [comment]
The way Glyphs does this is with anchors named caret_*, they are sorted by x coordinate and used in LigatureCaretByPos (see 3.4.2 in the doc).

**Comment by anthrotype** [comment]
@adrientetar thanks, that's for the LigatureCaretByPos. And the GlyphClassDef?

**Comment by schriftgestalt** [comment]
The GlyphClassDef for marks is determined by the GlyphsData.xml. (category=="Mark" and (subCategory=="Nonspacing" || subCategory=="Spacing Combining"))

**Comment by anthrotype** [comment]
thanks Georg. I guess could encode that information inside the UFO somehow, and if not available, ufo2ft could derive it from the codepoint and the `unicodedata` module.

**Comment by schriftgestalt** [comment]
You can make Glyphs to store the category and subcategory in the .glyphs file. Select all in Font view and hit cmd+opt+I (Edit > Info for Selection). The set the checkcoxes for both fields.

**Comment by davelab6** [comment]
Love it!

**Comment by brawer** [comment]
Actually, should the `table GDEF` statement really be generated by ufo2ft? Just wondering because this logic sounds quite specific to Glyphs.app, whereas ufo2ft is intended to process arbitrary UFOs. So perhaps it would be better if glyphsLib emitted a `table GDEF` statement into the `features.fea` file inside the generated UFO?

**Comment by schriftgestalt** [comment]
But where does the GDEF table comes from for Ufos from others sources?

**Comment by adrientetar** [comment]
I guess you either write it yourself or you have an app that does it automatically at export.

**Comment by schriftgestalt** [comment]
So the GDEF table is expected to be in the feature file?

**Comment by adrientetar** [comment]
Yes. FontForge writes `table GDEF` in UFOs, for instance.

**Comment by brawer** [comment]
Okay, I’d have a [patch](https://github.com/googlei18n/ufo2ft/compare/LigatureCaretByPos) but from this discussion, it sounds `ufo2ft` is really the wrong place for doing this. Instead, glyphsLib (and Glyphs.app) should be changed to write a `table GDEF` block into `features.fea` when they generate UFO. Would everyone agree?

**Comment by moyogo** [comment]
glyphsLib should definitely write the GDEF in the feature file.
ufo2ft could write one if none is defined, that would be useful, but nobody expects it to do that at the moment in UFO based workflows.

**Comment by brawer** [comment]
OK, will do it in glyphsLib then. See https://github.com/googlei18n/glyphsLib/issues/85.

**Comment by adrientetar** [comment]
> glyphsLib should definitely write the GDEF in the feature file.
ufo2ft could write one if none is defined,

Yea the UFO way can create duplication between these steps. While reading that issue I thought of having compiler extensions (kinda like GCC) then UFOs would have a "public.compilerFeatures" in their lib keys which compiler would fail if they don't have the feature.  
Then you only need to put the code in the compiler. Well, just a thought.
