### ISSUE TITLE
configure email notifications on pushes to fontmake-dev list

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/ufo2ft#93]
Could somebody with admin access set this up please?
I can't edit ufo2ft repository settings.

https://help.github.com/articles/managing-notifications-for-pushes-to-a-repository/

The email addess is fontmake-dev@googlegroups.com

https://groups.google.com/d/forum/fontmake-dev

**Comment by jamesgk** [comment]
OK I think this is done, assuming I set it up right.

**Comment by anthrotype** [comment]
Thanks James!
